
save_dir: ./results/Multi

env_args:
    env: ASRCAISim1
    env_config:
        config: 
        - ./configs/R4_contest_mission_config.json
        - ./configs/R4_contest_learning_config_M.json
        - ./configs/R4_contest_asset_models.json
        - ./configs/R4_contest_agent_ruler_reward_models.json
        - Manager:
            ViewerType: None
            Callbacks: {}
            Loggers: {}

policy_config:
    Learner:
        multi_port: true
        active_limit: 50
        is_internal: false
        populate:
            first_population: 1000
            interval: 1000
            on_start: false
        rating_initial: 1500
        rating_fixed: false
        initial_weight: null
        model_class: R4TorchNNSampleForHandyRL
        model_config:
            actionDistributionClassGetter: actionDistributionClassGetter
            use_lstm: true
            lstm_cell_size: 256
            lstm_num_layers: 2
            lstm_dropout: 0.2
            pos_conv:
                layers:
                    - ["Conv2d",{"kernel_size": 7,"out_channels": 32,"padding": 3,"stride": 2}]
                    - ["BatchNorm2d",{}]
                    - ["ReLU",{}]
                    - ["ResidualBlock",{
                        "layers":[
                            ["Conv2d",{"kernel_size": 3,"out_channels": 32,"padding": 1}],
                            ["BatchNorm2d",{}],
                            ["ReLU",{}],
                            ["Conv2d",{"kernel_size": 3,"out_channels": 32,"padding": 1}],
                            ["BatchNorm2d",{}]
                        ]}]
                    - ["ReLU",{}]
                    - ["Conv2d",{"kernel_size": 4,"out_channels": 64,"padding": 1,"stride": 2}]
                    - ["BatchNorm2d",{}]
                    - ["ReLU",{}]
                    - ["ResidualBlock",{
                        "layers":[
                            ["Conv2d",{"kernel_size": 3,"out_channels": 64,"padding": 1}],
                            ["BatchNorm2d",{}],
                            ["ReLU",{}],
                            ["Conv2d",{"kernel_size": 3,"out_channels": 64,"padding": 1}],
                            ["BatchNorm2d",{}]
                        ]}]
                    - ["ReLU",{}]
                    - ["Conv2d",{"kernel_size": 4,"out_channels": 128,"padding": 1,"stride": 2}]
                    - ["BatchNorm2d",{}]
                    - ["ReLU",{}]
                    - ["ResidualBlock",{
                        "layers":[
                            ["Conv2d",{"kernel_size": 3,"out_channels": 128,"padding": 1}],
                            ["BatchNorm2d",{}],
                            ["ReLU",{}],
                            ["Conv2d",{"kernel_size": 3,"out_channels": 128,"padding": 1}],
                            ["BatchNorm2d",{}]
                        ]}]
                    - ["ReLU",{}]
                    - ["AdaptiveAvgPool2d",{"output_size": 1}]
                    - ["Flatten",{}]
            dense:
                layers:
                    - ["Linear",{"out_features": 256}]
                    - ["ReLU",{}]
                    - ["ResidualBlock",{
                        "layers":[
                            ["Linear",{"out_features": 256}],
                            ["BatchNorm1d",{}],
                            ["ReLU",{}],
                            ["Linear",{"out_features": 256}],
                            ["BatchNorm1d",{}]
                        ]}]
                    - ["ReLU",{}]
                    - ["ResidualBlock",{
                        "layers":[
                            ["Linear",{"out_features": 256}],
                            ["BatchNorm1d",{}],
                            ["ReLU",{}],
                            ["Linear",{"out_features": 256}],
                            ["BatchNorm1d",{}]
                        ]}]
            merge:
                layers:
                    - ["ReLU",{}]
            value:
                layers:
                    - ["Linear",{"out_features": 64}]
                    - ["ReLU",{}]
                    - ["Linear",{"out_features": 64}]
                    - ["ReLU",{}]
            return:
                layers:
                    - ["Linear",{"out_features": 64}]
                    - ["ReLU",{}]
                    - ["Linear",{"out_features": 64}]
                    - ["ReLU",{}]
            action:
                layers:
                    - ["Linear",{"out_features": 128}]
                    - ["ReLU",{}]
                    - ["Linear",{"out_features": 128}]
                    - ["ReLU",{}]
    Initial:
        multi_port: false
        active_limit: null
        is_internal: true
        populate: null
        rating_initial: 1500
        rating_fixed: true
        initial_weight: null
        model_class: DummyInternalModel
        model_config: {}

train_args:
    name: Learner
    match_maker_class: BVRMatchMaker
    match_monitor_class: BVRMatchMonitor
    turn_based_training: false
    observation: false
    gamma: 0.99
    forward_steps: 64
    burn_in_steps: 8  # for RNNs
    compress_steps: 8
    entropy_regularization: 4.0e-3
    entropy_regularization_decay: 0.1
    exploration_config:
        use_exploration: true
        eps_start: 0.4
        eps_end: 0.4
        eps_decay: -1
        alpha: 7.0
        cycle: 16
    update_episodes: 10
    batch_size: 32
    minimum_episodes: 10
    maximum_episodes: 3000
    epochs: -1
    num_batchers: 8
    eval_rate: 0.1
    worker:
        num_parallel: 16
    lambda: 0.7
    policy_target: UPGO # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: TD # 'VTRACE' 'TD' 'MC'
    seed: 0
    policy_to_train: Learner
    policy_to_imitate: []
    imitation_beta: 0.6
    imitation_kl_threshold: 1.0
    imitation_loss_scale: 1.0
    imitation_loss_threshold: 1.0
    deterministic:
        g: 0.0
        e: 0.0

worker_args:
    server_address: ''
    num_parallel: 16

match_maker_args:
    seed: 12345
    match_config:
        warm_up_episodes: 0